added information regarding cyberglove_trajectory bug
shadow-robot/sr-visualization pull request #170
Opened 2017-05-10 16:28 UTC by mikramarc

Added information about cyberglove_trajectory package not working with sr_gui_cyberglove_calibration plugin

2017-05-11 08:36 UTC, mikramarc commented
Please do not merge yet

2017-05-12 16:41 UTC, AndriyPt requested changes

2017-05-12 16:41 UTC, AndriyPt commented on advanced/sr_gui_cyberglove_calibrator/src/sr_gui_cyberglove_calibrator/cyberglove_library.py
> +
this change is not needed

2017-05-16 11:38 UTC, AndriyPt requested changes

2017-05-16 11:38 UTC, AndriyPt commented on advanced/sr_gui_cyberglove_calibrator/test/test_cyberglove_calibrator.py
> +        self.filename = "mock_name"
why are you introducing this variable?

2017-05-16 14:25 UTC, AndriyPt approved these changes

2017-05-16 14:31 UTC, merged