Adding serial number to FingertipVisualizer plugin
shadow-robot/sr-visualization pull request #287
Opened 2022-04-07 15:13 UTC by maxzieba

## Proposed changes

Added serial number to Visual tab in FingertipVisualizer plugin. Agreed with Luke on adding the serial only to one tab. 
The reason is 2Hz of publishing rate for /diagnostics topic which would unnecessarily increase the loading time.

## Checklist

Before posting a PR ensure that from each of the below categories **AT LEAST ONE BOX HAS BEEN CHECKED**. If more than one category is applicable then more can be checked. Also ensure that the proposed changes have been filled out with relevant information for reviewers.

## Tests

- [ ] No tests required to be added. (For small changes that will be tested by CI/CD infrastructure).
- [ ] Added/Modified automated and PhantomHand CI tests (if a new class is added (Python or C++), the interface of that class must be unit tested).
- [ ] Manually tested in simulation (if simulation specific or no hardware required to test the functionality). 
- [X] Manually tested on hardware (if hardware specific or related).

## Documentation

- [X] No documentation required to be added.
- [ ] Added documentation (For any new feature, explain what it does and how to use it. Write the documentation in a relevant space, e.g. Github, Confluence, etc).
- [ ] Updated documentation (For changes to pre-existing features mentioned in the documentation).

2022-04-07 16:40 UTC, jeferal approved these changes

2022-04-08 13:50 UTC, giusebar requested changes

2022-04-08 13:50 UTC, giusebar commented on sr_fingertip_visualization/src/sr_fingertip_visualization/finger_widgets_visual.py
> +        while rospy.get_time() - now < 2:
can we change this 2 to a const? or add a comment with unit of measurement

2022-04-08 14:35 UTC, giusebar approved these changes

2022-04-08 14:35 UTC, merged